package demo.dao;

import demo.model.GAcUser;
import demo.model.GAcUserExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GAcUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_ac_user
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    long countByExample(GAcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_ac_user
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    int deleteByExample(GAcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_ac_user
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_ac_user
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    int insert(GAcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_ac_user
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    int insertSelective(GAcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_ac_user
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    List<GAcUser> selectByExample(GAcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_ac_user
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    GAcUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_ac_user
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    int updateByExampleSelective(@Param("record") GAcUser record, @Param("example") GAcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_ac_user
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    int updateByExample(@Param("record") GAcUser record, @Param("example") GAcUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_ac_user
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    int updateByPrimaryKeySelective(GAcUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_ac_user
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    int updateByPrimaryKey(GAcUser record);
}