server:
  port: 8762
spring:
  application:
    name: demo-service-provider
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
dubbo:  application:    name: ${spring.application.name} 
  registry:    address: nacos://127.0.0.1:8848
  scan:    base-packages: org.demo.common
  protocol:    name: dubbo
    port: 20880