server:
  port: 8763
spring:
  application:
    name: demo-service-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
nacos:
  discovery:
    server-addr: 127.0.0.1:8848
dubbo:
  application:
    name: demo-service-consumer
  registry:
    address: nacos://127.0.0.1:8848
  scan:
    base-packages: org.demo
  protocol:
    name: dubbo
    port: 20880