package demo.model;

import java.io.Serializable;

public class GAcUser implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_ac_user.id
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_ac_user.email
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_ac_user.password
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_ac_user.name
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table g_ac_user
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_ac_user.id
     *
     * @return the value of g_ac_user.id
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_ac_user.id
     *
     * @param id the value for g_ac_user.id
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_ac_user.email
     *
     * @return the value of g_ac_user.email
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_ac_user.email
     *
     * @param email the value for g_ac_user.email
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_ac_user.password
     *
     * @return the value of g_ac_user.password
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_ac_user.password
     *
     * @param password the value for g_ac_user.password
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_ac_user.name
     *
     * @return the value of g_ac_user.name
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_ac_user.name
     *
     * @param name the value for g_ac_user.name
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}