package demo.model;

import java.io.Serializable;

public class GItemDevice implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_item_device.id
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_item_device.name
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_item_device.des
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    private String des;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_item_device.uuid
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    private String uuid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_item_device.user_id
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column g_item_device.data_json
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    private String dataJson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table g_item_device
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_item_device.id
     *
     * @return the value of g_item_device.id
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_item_device.id
     *
     * @param id the value for g_item_device.id
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_item_device.name
     *
     * @return the value of g_item_device.name
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_item_device.name
     *
     * @param name the value for g_item_device.name
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_item_device.des
     *
     * @return the value of g_item_device.des
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    public String getDes() {
        return des;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_item_device.des
     *
     * @param des the value for g_item_device.des
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    public void setDes(String des) {
        this.des = des == null ? null : des.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_item_device.uuid
     *
     * @return the value of g_item_device.uuid
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    public String getUuid() {
        return uuid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_item_device.uuid
     *
     * @param uuid the value for g_item_device.uuid
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    public void setUuid(String uuid) {
        this.uuid = uuid == null ? null : uuid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_item_device.user_id
     *
     * @return the value of g_item_device.user_id
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_item_device.user_id
     *
     * @param userId the value for g_item_device.user_id
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column g_item_device.data_json
     *
     * @return the value of g_item_device.data_json
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    public String getDataJson() {
        return dataJson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column g_item_device.data_json
     *
     * @param dataJson the value for g_item_device.data_json
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    public void setDataJson(String dataJson) {
        this.dataJson = dataJson == null ? null : dataJson.trim();
    }
}