package demo.dao;

import demo.model.GItemDevice;
import demo.model.GItemDeviceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface GItemDeviceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_item_device
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    long countByExample(GItemDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_item_device
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    int deleteByExample(GItemDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_item_device
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_item_device
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    int insert(GItemDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_item_device
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    int insertSelective(GItemDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_item_device
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    List<GItemDevice> selectByExample(GItemDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_item_device
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    GItemDevice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_item_device
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    int updateByExampleSelective(@Param("record") GItemDevice record, @Param("example") GItemDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_item_device
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    int updateByExample(@Param("record") GItemDevice record, @Param("example") GItemDeviceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_item_device
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    int updateByPrimaryKeySelective(GItemDevice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table g_item_device
     *
     * @mbg.generated Sat Sep 07 15:55:48 CST 2019
     */
    int updateByPrimaryKey(GItemDevice record);
}