server:
  port: 8762
spring:
  application:
    name: push-service
  redis:
    host: 127.0.0.1
    port: 6379
    password: redis_f_6379
  datasource:
    name: test
    url: jdbc:mysql://127.0.0.1:3306/mybatis_demo?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull
    username: root
    password: Root123!
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 6000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
mybatis-plus:
  configuration:
    call-setters-on-nulls: true
  mapperLocations: classpath*:biz/demo/**/mapper/xml/*Mapper.xml
  typeAliasesPackage: biz.demo.**.entity
  # typeEnumsPackage: com.gdata.utils.enu.AlarmType
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 2
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    capital-mode: true
    #序列接口实现类配置,不在推荐使用此方式进行配置,请使用自定义bean注入
    # key-generator: com.baomidou.mybatisplus.incrementer.H2KeyGenerator
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 0
    logic-not-delete-value: 1
    configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
iot:
  port:
    wsPush: 8868